### ISSUE TITLE
Holds - Ticket Type Cards on dashboard views are showing inventory purchased from holds as still held

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#101]
**Steps to reproduce:**
- Create a hold of X tickets
- View the event dashboard and find that ticket type to confirm the Held count = X and note the Sold Count
- Buy 1 ticket from the hold

**Expected Behavior**
- Held ticket count should = the total held before the purchase - 1
- Sold ticket count should = the total sold before the purchase +1

**Actual Behavior**
- Held ticket count should = the total held before the purchase
- Sold ticket count should = the total sold before the purchase +1

For this event the total actual held is 320 (A hold of 20 tix and a hold of 300 tix), but the chart is still counting the 370 ticket hold that was completely claimed (the reports seem to be accounting for this properly):
![Big_Neon___Concert_and_Live_Event_Ticketing.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59934f6113749d001f2f5c80/125516c66e82c728ace21e0d46ca9d9d1cac86a681d6807c8752fe972c54334c280aa7145c8cf52d80676d04011b21c8180b0411b8a0d77cb4aa2e30c80351b882294d7ed43843a4b8851eb804b822834b82bebc8a4ec5ee3427b583895d220c4749d7ab0268f9d31e8a4afc59e04a5fa5163366e677377546921a7c2e792a.png)
![IMG_3325.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59934f6113749d001f2f5c80/125516c66e82c728ace21e0d46c1b9bd1cd1d0fbdaabf301b44fff9e2c4533317346f62928d5b479e8172953575b49a441585d41faf08b79aeb02e6c981e5ab38532022d8c6853beb2901eb80bbb258e4a85b7bd8348c7ed3823f5c6.jpeg)

**Comment by zmelamed** [comment]
Has this been deployed to prod?

**Comment by Krakaw** [comment]
Waiting for the :+1: on https://github.com/big-neon/bigneon/releases/tag/2019-04-12 and then that'll go in.

**Comment by harrisonlemon** [comment]
@zmelamed has this been released?
