### ISSUE TITLE
Event Management - Event with sales should not be allowed to move to externally ticketed,  externally ticketed cart routes should be blocked

### ISSUE THREAD

**Issue by harrisonlemon** [big-neon/bigneon#102]
**Actual Behavior**
- A client moved an event that was live and had pre-existing sales from `ticketed by Big Neon` to `Externally Ticketed`. 
  - It is now impossible to access the sales reporting
  - Users can still add tickets to their cart directly through the Ticket selection page (/tickets) in the web app.

**Expected Behavior**
- After tickets have been sold to an event I should not be able to switch the event to `Externally Ticketed`
- Externally ticketed events should redirect traffic from any part of the ticket purchase flow back to the event detail page and not let users add tickets to carts

**Steps to Reproduce:**
1. Create an event with tickets available
2. Buy a ticket
3. Switch the event to externally ticketed
4. Try and access event level reports to get info about that ticket from the web app
5. Try and navigate directly to the Ticket selection page and purchase a ticket

**Comment by Jasonvdb** [comment]
Disabling this with a message, let me know if you want the wording adjusted:
![Screenshot 2019-04-15 at 11 13 05](https://user-images.githubusercontent.com/5300488/56120961-7f1b1280-5f6f-11e9-8a6e-1a06c59422ce.png)
