### ISSUE TITLE
Roles - Doorperson permission does not allow app check-in access

### ISSUE THREAD

**Issue by harrisonlemon** [big-neon/bigneon#113]
**Steps to Reproduce:**
1. Navigate to Organization Settings
2. Select 'Team'
3. Add a user with 'Door Person' permissions
4. Accept the invite & login to Big Neon
5. Open the Big Neon App
6. Select 'Account'
7. Select 'Doorperson' from Event Tools
8. Choose an event to scan

**Expected Behavior:**

When a user is assigned to the 'Door Person' role, I expect that the user would be able to:
- Check-in tickets via the Big Neon app in Doorperson mode
- Manually check in tickets via Box Office

**Observed Behavior:**

- User with 'Door Person' role receives error message when attempting to use Door Person mode in app. 
-User is able to manually check tickets in via Box Office (desktop & mobile) without error. 

- Screengrab: https://cl.ly/97a3c2159232

**Comment by Timo614** [comment]
Going to move this back into the current sprint pile. I was able to confirm that I was able to check in users without issue so this seems to be a mobile app issue. 

I did see a permission issue in bn-web related to the codes endpoint (door people do not have CodeRead access) but that didn't prevent check-in access there.

**Comment by harrisonlemon** [comment]
@zmelamed Do we have an estimate on this?

**Comment by zmelamed** [comment]
@Krakaw @mikethetike @Timo614 can we get an update on where this stands when you have a moment. Are there any open questions? Thank you!

**Comment by Krakaw** [comment]
I am quite sure this was closed in big-neon/bn-api#1214 I will test and confirm
