### ISSUE TITLE
Customer Account - Customer is unable to update various account fields in App

### ISSUE THREAD

**Issue by harrisonlemon** [big-neon/bigneon#119]
**Steps to Reproduce:**

1. Open Big Neon app
2. Select 'Account' from bottom right hand corner
3. Select 'Account' from Account Details 
4. Add/Edit phone number & save changes

Screengrab: https://cl.ly/fc5231e69322

**Comment by iamjoshfrank** [comment]
Opened this in https://github.com/revelrylabs/bn-mobile-react/issues/758
