### ISSUE TITLE
Admin Event List - Held inventory count incorrectly reported

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#124]
related to big-neon/bigneon#101

The total held inventory count listed on the event card in the admin events list isn’t reporting the correct number.

The number shown is still counting the inventory sold from the hold as held.

**Steps to reproduce:**
- Create a hold of X tickets
- View the event dashboard to confirm the Held count = X and note the Sold Count
- Buy 1 ticket from the hold

**Expected Behavior**
- Held ticket count should = the total held before the purchase - 1
- Sold ticket count should = the total sold before the purchase +1

**Actual Behavior**
- Held ticket count should = the total held before the purchase
- Sold ticket count should = the total sold before the purchase +1

![BDB99696-A79D-4C41-AF91-9018FE87F6AF.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59934f6113749d001f2f5c80/125516c66e82c728ace21e0d46cab0b87adbd5f0d9a49e14fd79bdc00a12763e0822fa7a3ddcb379e7645e59582948dd374a4356bcbbd671f3e57862804e0ebfd96d5875c13813aeb08618b701ba228e498cb4ee824ad2f42f67b6d5db1063474f4dcbed5727a19f41c95df34ee7445da013366be2772431.jpeg)

**Comment by Timo614** [comment]
Triaged this, the problem stems from the frontend using the `tickets_held` value directly when it should be taking the `tickets_held` and subtracting the `sold_held` from it to figure out the remaining tickets. Will make a bn-web issue for this and push up a patch.

**Comment by mikethetike** [comment]
This looks fixed
