### ISSUE TITLE
My Events - List view Event Date/Time does not match event page Date/Time

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#127]
**Expected Behavior:** 
- As a ticket purchaser, when I navigate to "My Events" I should see the correct event date and time listed below the event name for each event.

**Actual Behavior:**
- As a ticket purchaser, when I navigate to "My Events" the listed event date/time below the event name does not match the event date/time listed on the event detail page.

<img width="1440" alt="Big_Neon_-_The_new_standard_in_event_ticketing" src="https://user-images.githubusercontent.com/456953/56517606-2ceb6b80-64f2-11e9-8821-a233849dd602.png">
<img width="1440" alt="Big_Neon_-_The_new_standard_in_event_ticketing" src="https://user-images.githubusercontent.com/456953/56517626-3a085a80-64f2-11e9-86d9-5f4e00e45c54.png">

**Comment by shanimal08** [comment]
I think this may still be an issue..
https://cl.ly/3de787b1a2a8

**Comment by Anziskavds** [comment]
Reviewed and the date and time matches as expected.

https://cl.ly/38be858df6c7

**Comment by Anziskavds** [comment]
Reviewed on Prod and information shows correctly as should.

https://cl.ly/36caee4906ef

https://cl.ly/ff5a58c332a8
