### ISSUE TITLE
Smart Holds - Mobile Optimized Holds List UI

### ISSUE THREAD

**Issue by harrisonlemon** [big-neon/bigneon#128]
**Context:** A user should be able to view the smart holds table on mobile web and quickly see in a table:

- Name of Promo Code

- Code

- Ticket Type

- Claimed from Hold

- Remaining

**Action Buttons:**

- If a user clicks the new Create Hold button they should see a form to create a new Smart Hold

- If a user clicks the Split Hold icon & they take action, they should see a success message that the code has been successfully split

- If a user clicks the Copy Link icon they should see a success message that the link has been successfully copied

- If a user clicks the Edit icon they should see a form to edit the code details

**UI**: 
https://share.goabstract.com/349cbab4-36ed-47b6-a8f4-8bd29877c30b?
https://share.goabstract.com/84360bda-b078-4e98-8daa-b1cfd2fb4e75?
https://share.goabstract.com/73ee9018-acf1-4c6d-b0bd-77b4bfc91c86
https://share.goabstract.com/d8f5043c-83d8-4a4a-986e-339e1fe01770

![image](https://user-images.githubusercontent.com/456953/57470329-65eb4600-723d-11e9-8b37-263d4c4cdb38.png)

![image](https://user-images.githubusercontent.com/456953/57470317-5ec43800-723d-11e9-80bc-913ecc8c32b9.png)

**Comment by harrisonlemon** [comment]
@zmelamed Do we have an estimate on this? The promo code mobile UI update is ready to release. Given the use & interchangeability of these two sections, it would make our product look unfinished/unpolished if we had a significant gap in one area over the other. Is it possible to release these two updates at the same time?

**Comment by zmelamed** [comment]
I've added all the UI and prioritized in up next, should be a reasonably quick one to knock out following the same patterns as promo codes
