### ISSUE TITLE
Event Creation - Cannot save events with ticket types

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#134]
When publishing a new event with any ticket types an error `Failed to save event` appears, but event publishes, ticket types do not save.

When you attempt to edit the event to add ticket types you cannot, you receive the same `Failed to save event` error.

Screencast: https://cl.ly/ce80930c12e8

https://sentry.io/organizations/big-neon-5x/issues/997433599/?project=1407122&referrer=webhooks_plugin

```
Error: /events/{event_id}/ticket_types is expecting these fields: name, price_in_cents, start_date, end_date, limit_per_person, visibility
extra	{"arguments":"[{\"message\":\"/events/{event_id}/ticket_types is expecting these fields: name, price_in_cents, start_date, end_date, limit_per_person, visibility\",\"name\":\"Error\",\"stack\":\"Error: /events/{event_id}/ticket_types is expecting these fields: name, price_in_cents, start_date, end_date, limit_per_person, visibility\\n    at t._requiredFieldsPresent (https://www.bigneon.com/static/js/main.0fee88b3.js:1:621618)\\n    at t.<anonymous> (https://www.bigneon.com/static/js/main.0fee88b3.js:1:622280)\\n    at o (https://www.bigneon.com/static/js/main.0fee88b3.js:1:619653)\\n    at Object.next (https://www.bigneon.com/static/js/main.0fee88b3.js:1:618957)\\n    at https://www.bigneon.com/static/js/main.0fee88b3.js:1:618866\\n    at new Promise (<anonymous>)\\n    at r (https://www.bigneon.com/static/js/main.0fee88b3.js:1:618643)\\n    at Object.create (https://www.bigneon.com/static/js/main.0fee88b3.js:1:622087)\\n    at https://www.bigneon.com/static/js/0.1a7e5fd5.chunk.js:1:43116\\n    at new Promise (<anonymous>)\\n    at e.<anonym..."}
```

**Comment by Krakaw** [comment]
@mikethetike fix this issue in live. Netlify rebuilt the dependencies which included the `latest` bn-api-node that required the `visibility` field that is only coming to bn-web in v1.0.376.

Two solutions here. The one is as @mikethetike mentioned to lock the bn-api-node version in package.json. @Jasonvdb we need to stay aware of this. The other is to lock netlify to a build version http://cl.ly/f84579753804/Image%2525202019-04-25%252520at%2525204.39.00%252520AM.png but we also need to be aware then that pushing to the `live` branch won't automatically deploy.
