### ISSUE TITLE
Event Creation - Re-organize form inputs in Event Details

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#136]
- [ ] Font sizes, colors, and families for input labels, placeholder text, and values should match the design spec
- [x] Field label updates
  - `Event End Date` -> `End Date`
  - `Event End Time` -> `End Time`
  - `Event Video Url` -> `Featured media url` 
  - `Age Limit` `(Custom Age Limit)` -> `Select Age Limit` `or customize...`
  - `Age Limit` `(Select Age Limit)` -> `Custom Age Limit` `or select existing...`
  - `Private Access Code (Disables Public Access Without Code)` -> `Private Access Code`
- [x] Field sizing should be more intentional based on the content that is going to be added--see the spec as a guide for relative field sizing
- [x] Fields should be listed in the following order from top down by row:
  - Desktop
    1. `Event Name`,`Venue`
    2. Field Toggle: `Add Top Line Info`
    3. `Show Date`, `Show Time`, `Door Time`
    4. `End Date`, `End Time`
    5. `Additional Information`
    6. `Select Age Limit`
    7. Field Toggle: `Add media`
    8. Field Toggle: `Manually adjust event status`
    9. Field Toggle: `Require password to view event`

  - Mobile

    1. `Event Name`,`Venue` 
    2. Field Toggle: `Add Top Line Info`
    3. `Show Date`
    4. `Show Time`, `Door Time`
    5. `End Date`, `End Time`
    6. `Additional Information`
    7. Field Toggle: `Select Age Limit`
    8. Field Toggle: `Add media`
    9. Field Toggle: `Manually adjust event status`
    10. Field Toggle: `Require password to view event`
- [ ] Special Field Spec
  - `Venue`
    - If only one venue is available to the org it should be selected by default
  - `Select Age Limit`: 
    - Defaults to dropdown `Select Age Limit` mode with a toggle `or customize...` when clicked the input switches to a free entry input field with the label `Custom Age Limit` and the toggle switches to `or select existing...`
  - Field Toggle: `Add media`
    - When clicked the `Featured Media Url` input should appear
    - This will develop into a more robust media embedding feature, for now just re-purpose the current `Event Video Url` field
  - Field Toggle: `Manually adjust event status`
    - The exposes the `Event Status` input which is defaulted to `Auto`. 
    - If this is not set to `Auto` anything the field should not be hidden behind the toggle.
  - Field Toggle: `Require password to view event`
    - The exposes the `Private Access Code (Disables Public Access Without Code)` label and input should be changed to `Private Access Code`
    - If this is set it should not be hidden behind the toggle
- [x] `Event Type` should be hidden and defaulted to Music until we have a larger volume of users with alternative event types
- [x] Artist Image thumbnails should be square to accommodate Spotify images 

https://share.goabstract.com/19823e7f-af85-4796-b05a-725adf8815d2
![image](https://user-images.githubusercontent.com/456953/56880191-a6aeb800-6a10-11e9-953a-9c7b58a0cdc7.png)

**Comment by Krakaw** [comment]
@Jasonvdb a quick note about the `door_time`, also update the `redeem_date` field to be the same as the door_time if it is changed.

**Comment by Jasonvdb** [comment]
@zmelamed we're currently saving the `Featured media url` but I've just seen we're not actually using it on the event view page or anywhere else that I'm aware of.

**Comment by zmelamed** [comment]
That’s correct, that’s coming up very soon in separate issues like #78 and #79, but the consumer facing work is out of scope relative to this issue

**Comment by Jasonvdb** [comment]
API seems to be returning all venues for all orgs. Moving the auto venue select into another issue so we can get in what we have so far.  https://github.com/big-neon/bn-web/issues/1389

**Comment by Jasonvdb** [comment]
@Krakaw Redeem date was always just kept the same as door time before saving: `eventDetails.redeem_date = eventDetails.door_time;`
