### ISSUE TITLE
Reports - Various reports reflect incorrect sales data

### ISSUE THREAD

**Issue by harrisonlemon** [big-neon/bigneon#139]
Various reports (listed below) reflect incorrect or inconsistent sales data. Reports & observed behaviors listed below:

- Event Summary (screencap https://cl.ly/4b405f4f2010)

1. 'Price' column reflects full face value of ticket when a discount has been applied. Discount is calculated in 'Total' column.

- Event Audit (screencap https://cl.ly/acae3e2ab3e4)

1. 'Price' column reflects full face value of ticket when a discount has been applied. Discount is calculated in 'Total' column.

- Event Summary Audit (screencap https://cl.ly/42ba1b99723b)

1. 'Price' column reflects full face value of ticket when a discount has been applied.

2. Total Sales column is all $0 regardless of sales data

**Comment by Timo614** [comment]
@zmelamed https://cl.ly/42ba1b99723b

'Price' column reflects full face value of ticket when a discount has been applied.

The column there though is 'Face' not 'Price' so wondering if this is intentionally for that particular item. Should it always show as the full value of the ticket right regardless of any discount application? The other issues I can reproduce / am fixing in a PR just confirming before I change that to price.

**Comment by harrisonlemon** [comment]
@zmelamed @Timo614  'Face' refers to the customer-facing ticket price, as opposed to the set base ticket price or the net ticket price*. Reports will have different criteria, depending on accessibility (which users can access the reports) and how detailed the report is. 

The Event Summary Audit is accessible by org-level users only, but could be shared with 3rd parties.  There are 2 issues occurring here:

1. The 'Total' column does not calculate. All 'totals' are $0 regardless of sales data. This is an incorrect calculation.

2. The word 'Face' is misrepresented. The face value is what the consumer pays, not the price of the ticket. The Audit here should represent the face value of the ticket. Otherwise we would not need to breakout a separate line item. 

*Net ticket price = base ticket price less inclusive fees
