### ISSUE TITLE
Event Creation - Re-organize form inputs in Ticketing

### ISSUE THREAD

**Issue by harrisonlemon** [big-neon/bigneon#141]
Context: Re-organize Ticket Type Form so it's easier to manage additional options for ticket types
- [x] Field label updates
  - `Sale Start Date` -> `Start Date`
  - `Sale Start Time` -> `Start Time`
  - `Tickets` -> `Select Ticket Type`
  - `Ticket sale end time` -> `Sales End`
  - `Sale End Date` -> `End Date`
  - `Sale End Time` -> `End Time`
  - `Ticket Limit` -> `Max Tickets Per Customer` 
  - `Increment` -> `Cart Qty Increment`
  - `Ticket Description` change placeholder text to `Short description of this ticket type`
- [x] Field sizing should be more intentional based on the content that is going to be added--see the spec as a guide for relative field sizing
- [x] Fields should be listed in the following order from top down by row:
  - Desktop
    1. `Ticket Name`,`Qty`,`Price`
    2. `Sales Start`, [Blank or `Start Date`, `Start Time` or `Select Ticket Type` ]
    3. `Sales End`, [Blank or `End Date`, `End Time`]
    4. `Ticket Description`
    5.  Field Toggle: `Set max tix per customer`
    6. Field Toggle: `Set visibility/access rules`
    7. Field Toggle: `Set box office/door pricing`
    8. Field Toggle: `Enforce qty increment`
    9. Section/Field Toggle: `Schedule a price change`

  - Mobile
    1. `Ticket Name`
    2. `Qty`,`Price`
    3. `Sales Start`
    4. [Blank or `Start Date`, `Start Time` or `Select Ticket Type` ]
    5. `Sales End`
    6. [Blank or `End Date`, `End Time`]
    7. `Ticket Description`
    8.  Field Toggle: `Set max tix per customer`
    9. Field Toggle: `Set visibility/access rules`
    10. Field Toggle: `Set box office/door pricing`
    11. Field Toggle: `Enforce qty increment`
    12. Section/Field Toggle: `Schedule a price change`

- [x] Special Field Spec
  - `Sales Start`
    - Options: `Immediately`, `At a specific time`, `When sales end for...`
    - `At a specific time` should expose the `Start Date` and `Start Time` field
    - `When sales end for...` should expose the `Select Ticket Type` field with the list of ticket types
  - `Sales End`: 
    - Options: `Door Time`, `Event Start`, `Event End`, `At a specific time`
    - `At a specific time` should expose the `End Date` and `End Time` field
  - Field Toggle: `Set max per customer media`
    - When clicked the `Max Tickets Per Customer` input should appear
    - If this is not set to the default of 10 the input should not be hidden
  - Field Toggle: `Set visibility/access rules`
    - The exposes the `Visibility` dropdown 
    - If this is not set to `Always Visible` the field should not be hidden behind the toggle.
  - Field Toggle: `Set box office/door pricing`
    - The exposes the `Box Office/Door Pricing` input
    - If this is set it should not be hidden behind the toggle
  - Field Toggle: `Enforce qty increment`
    - The exposes the `Cart Qty Increment` input
    - If this is set it should not be hidden behind the toggle

![image.png](https://images.zenhubusercontent.com/5c8c16315df6d54b7b125005/2a3aec34-0ec5-4d30-b5cf-c7ff2f67c137)

**Comment by Jasonvdb** [comment]
I've got all this done, except for the box office price. Not sure why that's commented out still, going to investigate/test to see if that's alright to place back.

**Comment by Anziskavds** [comment]
@Jasonvdb Reviewed and it is in the correct order as stated above on web and mobile web but I see "Box Office/Door pricing" is still not on either web or mobile web as per your comment. Have you gotten time yet to look at it?

**Comment by Jasonvdb** [comment]
@Anziskavds haven't had time yet, think we should maybe open a separate issue to add box office pricing so we can close this one so long.

**Comment by Anziskavds** [comment]
Tested work as expected. Based on a prior request box office is no longer displayed.
