### ISSUE TITLE
Ticket Transfer - On devices with smaller screens transfer button is off screen and user can't get through transfer process

### ISSUE THREAD

**Issue by harrisonlemon** [big-neon/bigneon#142]
Customer reported (with screenshots & video):

User is unable to access the 'transfer tickets' button. Because the 'transfer tickets' button is off screen, the user is not able to access the transfer button by scrolling. 

Device: iPhone SE

**Comment by zmelamed** [comment]
Closing this as it's already captured in big-neon/bigneon#109
