### ISSUE TITLE
Transfers - A user should be able to cancel a ticket transfer they created until the transfer is accepted

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#145]
**Context:** If a user creates a ticket transfer request and that ticket has not yet been accepted/added to another users wallet, the transferrer should be able to cancel the transfer request

- When a user has a ticket in a transfer state they should be presented with an action button to `Cancel Transfer`.
- When a the `Cancel Transfer` button is clicked, the user should see a confirmation dialog `Are you sure you want to cancel this ticket transfer?`
- If the user clicks `Yes, cancel transfer`:
  - The transfer should be expired
  - A record of the transfer cancellation should be stored as part of that orders history
  - The transferrer should receive an email receipt that their ticket transfer was successfully cancelled.
  - The original transferee should receive a message through the channel the transfer was sent notifying them that the transfer was cancelled by the originating transferrer

related to big-neon/bigneon#146

**Comment by mikethetike** [comment]
Any update on this? I see it's in progress, but can't see why or who is working on it

**Comment by Timo614** [comment]
The API side was done ages back -- this was from back when we used to make separate issues for each component. Not sure on the web side so may need @Krakaw to chime in there. May have been something handled with a separate issue?

**Comment by Krakaw** [comment]
This has been completed and is in production
http://cl.ly/2c0ca640c904
