### ISSUE TITLE
Ticket Transfers - Reminder drip notifications

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#148]
**Context/Problem:** If a user doesn't accept their ticket transfer there can be issues the night of the event scrambling to sort it out at the door. A transferrer may mistakenly send a ticket to the wrong address and not realize the intended transferee didn't receive the transfer. 

**Hypothesis:** By sending reminders to both parties until the transfer is accepted/cancelled we will reduce friction at the door/night of event and reduce the likelihood of customer support having to track down ticket transfers

A **transferrer** should receive notifications letting them know their transfer has not yet been accepted, including the transfer details, instructing them to remind their friend or cancel and resend the transfer

A **transferee** should receive a series of time based notifications reminding them to accept their ticket transfer

**Comment by Timo614** [comment]
What were we thinking here interval wise? From the above it seems like we were thinking:
- Transferrer receives these regularly (every 2 days?) until the event ends or the transfer is completed/cancelled?
- Transferee receives these based on some sort of schedule. Were you thinking something like: 1 day later, 3, 6, 10, 15, etc until the event ends or the transfer is completed/cancelled?

**Comment by zmelamed** [comment]
The cadence is still in discussion so if you can set this up to be flexible that'd be great. The frequency should actually accelerate as the event approaches... T -0, T -1, T -3, T -7 etc. So when you set up the logic it should be based on the date/time of show

**Comment by zmelamed** [comment]
I imagine we should create a single template that accepts the variable header which is sent from the backend based on the urgency/days until event.

We want to have a flexible enough system that we can try out lots of different copy time intervals.

T-7, T-1, T-0 sender emails:
![image.png](https://images.zenhubusercontent.com/5c8c16315df6d54b7b125005/6c50c6f0-9d22-4675-bc4d-aa65889e752c)

T-7, T-1, T-0 receiver emails:
![image.png](https://images.zenhubusercontent.com/5c8c16315df6d54b7b125005/bd6bfe80-33b3-40c8-90fa-142e52ac2d3c)

The copy for receiver SMS should be the same as the headers of the receiver email for now.

**Comment by Timo614** [comment]
Sounds good -- will make adjustments for that in the bn-api PR. :+1:

**Comment by Timo614** [comment]
@zmelamed for the drips I have them occur at the same time as the event itself. 

The copy for the day of the event one though mentions "tonight" so guessing for that day we'll want to send it out at least a few hours prior? Obviously we'll probably want to change that depending upon the time thinking < 5 PM = "today", >=  5 PM = "tonight"?

**Comment by nine-tari** [comment]
This may be hard to QA but I think we'll be adding the ability to use minutes instead of days prior to the event start to help with that so should be easier once it's in place. I put this in review now since the logic is there and would work just could take days to see them appear depending upon the event start dates set.

If the script was not run in develop or beta older events may not get these drips.

**Comment by Anziskavds** [comment]
Tested on Beta and is working as expected. Both the parties received notification emails that the transferred tickets haven't been claimed yet.

**Comment by Anziskavds** [comment]
Tested on Prod and is working as expected.
