### ISSUE TITLE
Scanning/Check-in - Ticket check-in log

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#150]
Context: A doorperson should be presented with any check-in activity related to a ticket when scanning a ticket that has already been checked-in.

This should include:
Time Since Scan
Scanners Information - First name last initial 
Method - Guest List

**Comment by harrisonlemon** [comment]
App check-in tbd - test app access pending

**Comment by Anziskavds** [comment]
Tested on Prod. Check-in and scanning of tickets work as expected. Also if a ticket was already scanned or checked in it gives the details when it was scanned or checked in and by who.
