### ISSUE TITLE
Ticket Transfers - Improve Accept Transfer error experience

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#151]
**Context**: If a transferee attempts to accept a transferred ticket and that ticket transfer has been cancelled or expired they should be receive a message explaining with context, and be given the most direct path to acquiring tickets an alternate way such as buying them to try and convert them into a buyer

**Comment by Timo614** [comment]
Note: we no longer expire transfers (pending, completed, or cancelled but no more expirations) so that aspect of this issue is no longer applicable. See: #154

**Comment by zmelamed** [comment]
https://share.goabstract.com/6e52c96b-414a-4687-aa80-ce024fb0c8a1
![image.png](https://images.zenhubusercontent.com/5c8c16315df6d54b7b125005/05243bad-7a96-44e1-83eb-7bb62592b09e)
![image.png](https://images.zenhubusercontent.com/5c8c16315df6d54b7b125005/fd9aef30-a220-473d-83ea-7c30e0ae1a61)

**Comment by Anziskavds** [comment]
Tested on Beta and the sender received a cancellation confirmation email and the receiver received a email informing them that the ticket transfer was cancelled and they have the option to click on "find more tickets" from the email and purchase tickets successfully. Seems like it's working as expected.

**Comment by Anziskavds** [comment]
Tested on Prod. When a ticket transfer was cancelled the sender and receiver receives a notification email to inform them of the cancelled transfer. The receiver can click on "find more tickets" from the email to purchase tickets if they wish to do so. When the transfer was cancelled and the receiver attempt to accept the transferred tickets after the transfer was cancelled the receiver gets "This ticket transfer was cancelled" and gives the receiver the option to click on "Find other events" to purchase tickets if they wish to do so. Looks like it is working as expected.
