### ISSUE TITLE
Facebook authentication failed when accepting transger

### ISSUE THREAD

**Issue by Anziskavds** [big-neon/bigneon#160]
Steps to reproduce:
* Transfer tickets email send to a not registered email address. 
* After receiving the email with the transferred tickets and I click on accept my tickets, the page open but I get a "Facebook authentication failed" error message.

See below
https://cl.ly/e0423ea5bdc5

**Comment by Tas4tari** [comment]
Duplicate to https://app.zenhub.com/workspaces/big-neon-engineering-5c8c172f5df6d54b7b12500c/issues/big-neon/bigneon/161
