### ISSUE TITLE
Release 2019-05-16

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bigneon#164]
#### Released versions
 * API Version: [1.0.115](https://github.com/big-neon/bn-api/releases/tag/1.0.115)
 * Web Version: [v1.0.396](https://github.com/big-neon/bn-web/releases/tag/v1.0.396)
 * Middleware: [v2.0.7](https://github.com/big-neon/bn-api-node/releases/tag/v2.0.7)
#### Overview
Backend ticket enhancements and bug fixes

#### Specifics
 * Adding redemption details to ticket_instances  big-neon/bigneon#150
 * Don't return deleted holds in holds/{}/children - Fixes a bug in deleting hold children
 * Tiered ticket type edit bug big-neon/bn-api#1268
 * Disable nullifying email address big-neon/bn-api#1256
 * Fix transfer issue with TicketInstance#find_for_display

**Comment by Tas4tari** [comment]
This has been successfully released.
