### ISSUE TITLE
SEO - 301 Redirect all traffic from studio.bigneon.com to www.bigneon.com

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#169]
Context: Currently we're seeing google search results that drive traffic to studio.bigneon.com instead of www.bigneon.com. This impacts overall ranking of the www.bigneon.com domain. 301 Redirect (permanently moved) all traffic to www.bigneon.com to remedy this problem.

**Comment by zmelamed** [comment]
https:// isn't redirecting and needs to

**Comment by Krakaw** [comment]
I'll chat to @leet4tari we'll need to use a cloudfront distribution to enable SSL.

**Comment by Krakaw** [comment]
@leet4tari https://studio.bigneon.com does not redirect but it does show the site.

**Comment by Krakaw** [comment]
I've implemented a new cloudfront distribution that redirects both http and https
![image.png](https://images.zenhubusercontent.com/5c91ad12b65bca7678bd1e8f/4bcb2de6-3e6e-4249-94f2-4ce005d5fe4a)
![image.png](https://images.zenhubusercontent.com/5c91ad12b65bca7678bd1e8f/6838f541-0b2c-4283-ad34-430fe0d1767c)
