### ISSUE TITLE
Reporting - Org Level CSV Exporting Fails  

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#173]
Expected Behavior: Clicking Export CSV from the Org Level Transaction Detail reports view results in the download of a CSV file containing all transactions.

Actual Behavior: Clicking Export CSV results in a `Failed - Network Error` for our client PW.
https://cl.ly/0b72546ad8fa

@Timo614 I believe you already worked on this but I couldn't find the ticket anywhere

**Comment by Timo614** [comment]
https://github.com/big-neon/bn-web/issues/1441 was the original ticket. It looks like it came in with 1.0.399 but production is on 1.0.396.

**Comment by Timo614** [comment]
https://app.zenhub.com/workspaces/big-neon-engineering-5c8c172f5df6d54b7b12500c/issues/big-neon/bn-web/1469 is the zenhub issue -- it's in the merged pile.

**Comment by Anziskavds** [comment]
Reviewed:

-I was able to export the CSV reports successfully.

**Comment by Anziskavds** [comment]
Tested on Prod and the CSV report exported successfully.
