### ISSUE TITLE
Event Detail Page - Add event info to top of page on mobile web

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#174]
**Context:** Currently when a user navigates to the ticket selection view they lose context about the event they are buying tickets for. This is particularly problematic because users get promo links that drive them directly into the ticket selection view.

A user should see the following details at the top of the ticket selection view on mobile:
Event Name
Event Venue - Including City, State
Event Date - Event Show Time
Event Image Thumbnail
Link to View The Event Details that will bring them back to the event details view.

The event name should be ellipse'd if it extends beyond 1 line
![image.png](https://images.zenhubusercontent.com/5c8c16315df6d54b7b125005/f8cb4b28-a897-4e8a-bcd8-3ce06e974b9e)
Event info design: https://share.goabstract.com/483b7a8c-4719-4cd4-b47c-bb9b7290e03c?mode=design&sha=36f627ab12faf69d3b9d506eaf308450621e20c1

**Comment by Krakaw** [comment]
@zmelamed the code is ready, we are waiting for approval before pushing this live.

**Comment by Jasonvdb** [comment]
Anybody know what's happening with this one? Think we were waiting for approval from business on the designs. Code is there, it's just commented out. Adding this in would be a quick 1min job and we can close. @Tas4tari @harrisonlemon

**Comment by harrisonlemon** [comment]
@ridley-tari Take a peek? Client request from May waiting approval. This looks good to me. Thanks!

**Comment by ridley-tari** [comment]
@harrisonlemon @Jasonvdb please proceed. Who is the client? cc @Tas4tari

**Comment by harrisonlemon** [comment]
Requested by Espee & Public Works

**Comment by Anziskavds** [comment]
Tested on develop and majority tested successful, I only found that on develop we have the **continue** option to click on and on the above design **Select Tickets**. Which one is the correct on to use?
@Jasonvdb

**Comment by Jasonvdb** [comment]
Ok thanks that's fine, the button is currently like that live. Just updated the event details at the top so if that's good we can close. 

If the button wording needs to change to match this specific design please someone on the product/project management side make an issue and I'll hop on that quick 👍

**Comment by ridley-tari** [comment]
@harrisonlemon any strong opinion here? I'd say continue but would like to default to you since you have more familiarity at this point.

**Comment by harrisonlemon** [comment]
@Jasonvdb Can you please add time zone to the event details after the listed time?

'Continue' is preferred over 'select tickets' - we are good to go here. Thanks!

**Comment by Jasonvdb** [comment]
Cool done 👍 
![Screenshot 2019-07-24 at 09 40 05](https://user-images.githubusercontent.com/5300488/61774386-0a216980-adf7-11e9-8577-518f4fd4783d.png)

**Comment by Anziskavds** [comment]
Tested successful on develop.

**Comment by Anziskavds** [comment]
Tested successful on Beta for mobile web.

**Comment by Anziskavds** [comment]
Tested successful on Prod.
