### ISSUE TITLE
Ticket Transfers/Fans - A user who receives a ticket transfer needs to be added to the Fans list of the organization

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#178]
Context: Currently it seems that users who have accepted a ticket transfer don't show up in the org level fans report. Every person that purchases or holds a ticket to an event should show up in the fan report.

**Comment by Timo614** [comment]
I noticed the events#search_fans logic also does not include these users but also includes the event interested users. 

Will also include the event interested users in the fan list (also currently missing).

I'll make adjustments in the morning to also include those ticket holders for that method as part of this card.

Looks like it's used for two things:
- `/events/{id}/fans` endpoint
- BulkEventFanListImportExecutor which seems to be a sendgrid import job

At the moment the above will only include the purchasing users and the event interested users.

https://github.com/big-neon/bn-api/blob/79b9d9d8ea386a6c1605b96a88fbc224f94be000/api/src/domain_events/executors/marketing_contacts/bulk_event_fan_list_import.rs#L96

**Comment by Timo614** [comment]
Also noticed a bug with the organization#has_fan logic to view a single fan. It only currently checks for purchases and the purchasing user so would return an error if you opened up a fan with a box office purchased order at the moment. Will adjust that in this branch.

**Comment by nine-tari** [comment]
Just going through the pile looks like this was merged while I was out. If you check the PR there were a few other modifications made for bugs I noticed. 

I'll file some new bug issues for the remaining bugs I noticed (not related to the new changes but I noticed them while going through like the order show page on bn-web for refunded orders having issues etc).

**Comment by Anziskavds** [comment]
Tested on Beta and is working as expected.

**Comment by Anziskavds** [comment]
Tested on Prod and is working as expected
