### ISSUE TITLE
Ticket Transfers - After sending a ticket transfer, the sender should receive a confirmation email with a link to cancel the transfer 

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#181]
**Context**: After creating a ticket transfer, the sender should receive an email confirmation with information related to the ticket transfer, as well as a link to Cancel the transfer that leads them through a web flow to cancel the transfer. 

Related to: #145

![ticket_transfer_sender_success.png](https://images.zenhubusercontent.com/5c8c16315df6d54b7b125005/b66e0006-bc2c-443a-a311-19e048b0a1c7)
![ticket_transfer_mistake_cancel.png](https://images.zenhubusercontent.com/5c8c16315df6d54b7b125005/529a2282-7f61-4845-9fa5-4d8b4f902d1c)
![ticket_transfer_mistake_cancel.png](https://images.zenhubusercontent.com/5c8c16315df6d54b7b125005/330ab93c-9712-4993-9600-29015ccfdbbc)
![image.png](https://images.zenhubusercontent.com/5c8c16315df6d54b7b125005/6bfbc481-10fe-46eb-a44b-9a9be3fbf881)

**Comment by Jasonvdb** [comment]
@zmelamed once they've clicked on the cancel link in the email and they're on the web, do you think we should get them to authenticate first or make the api work without auth first?

**Comment by Jasonvdb** [comment]
Waiting for: https://github.com/big-neon/bn-api/issues/1265

**Comment by mikethetike** [comment]
Still need the api for this one

**Comment by mikethetike** [comment]
@zmelamed we need a sendgrid template for this as well

**Comment by zmelamed** [comment]
template id `d-3b5d9abc10ea41449b045eca7d1e31df` name: `BN_transfer_confirmation_sender`
Double check that it's at least sending `event_name` `receiver_address` `transfer_cancel_url`

**Comment by Tas4tari** [comment]
@mikethetike the template for this has been added. Can you please confirm if the API has been done

**Comment by Timo614** [comment]
@zmelamed is there a template for a receipt for when a user sends the tickets to an existing user / a direct transfer? If it's even worth sending one at all given the user won't need to prod the receiver to accept them at least in that case.

For now in the PR I'm about to push up direct transfers receive no email as this template includes a cancel link and some specific text about having them claim the ticket.

**Comment by Anziskavds** [comment]
@mikethetike Will you please confirm if the above mentioned is done yet? I tested but doesn't seems to be working.

**Comment by Timo614** [comment]
I confirmed locally I see it go out on master:

```
{"level":"INFO","time":"[2019-07-04][12:13:09]","target":"server","message":"Blocked communication","body":null,"comm_type":"EmailTemplate","destination_addresses":["user156171373559313517@tari.com"],"source":{"addresses":["noreply@bigneon.com"]},"template_data":[{"artist_headliners":"Artist 1561713687","artist_other":"","event_age_limit":"18","event_date":"Sunday, 7 July 2019","event_doors_open_time":"3:00 AM PST","event_event_start":"6:00 PM PDT","event_id":"9adb6084-f935-4813-8651-05bb8c8f25f9","event_name":"It's my party","event_promo_url":"http://localhost/noimg.png","organization_id":"af59a123-b573-450a-b14c-20c57ddd95a1","organization_name":"Jazzy_1561713687","receiver_address":"nine@bigneon.com","sender_name":"User S.","transfer_cancel_url":"http://localhost:3000/my-events?event_id=9adb6084-f935-4813-8651-05bb8c8f25f9","transfer_id":"48e32d2d-52b9-4890-b050-e324e1eba086","venue_address":"address","venue_city":"city","venue_country":"the best country","venue_map_link":"https://www.google.com/maps/place/address%2Ccity%2CCA%2Cthe+best+country/","venue_name":"Test venue_1561713687","venue_phone":"5555555555","venue_postal_code":"2222","venue_promo_image_url":"","venue_state":"CA"}],"template_id":"d-3b5d9abc10ea41449b045eca7d1e31df","title":"BigNeon: Ticket transfer sent"}
```

The `d-3b5d9abc10ea41449b045eca7d1e31df` is the template used for the email (I have sending disabled to avoid spamming the random addresses but confirmed earlier with my own email I got it as well in the associated PR).

My guess is that the two staging environments may be missing the env var or if we went forward with the plan to make a new sendgrid account for those environments it may be missing the template.

**Comment by Anziskavds** [comment]
Tested Develop and Beta and tested successfully as expected on web and mobile web

**Comment by Anziskavds** [comment]
Tested on Prod on Mobile(Android) and web and is working as expected
