### ISSUE TITLE
Marketing - Facebook Pixel Integration

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#182]
Context: You can use the Facebook pixel to track your website visitors' actions. This is called conversion tracking. Tracked conversions appear in the Facebook Ads Manager and the Facebook Analytics dashboard, where they can be used to analyze the effectiveness of your conversion funnel and to calculate your return on ad investment. You can also use tracked conversions to define custom audiences for ad optimization and dynamic ad campaigns. Once you have defined custom audiences, we can use them to identify other Facebook users who are likely to convert and target them with your ads.

- An org admin or higher should be able to set the orgs Facebook Pixel in the orgs Marketing tab of Studio
- An org member should be able to set a Facebook Pixel for a specific event which will override the org level Facebook Pixel
- If a Facebook Pixel is available the following base code (https://developers.facebook.com/docs/facebook-pixel/implementation#base-code) should be injected in the `<head></head>` of the event detail page and all subsequent pages related to that events checkout funnel with `your-pixel-id-goes-here` replaced with the org provided pixel:
```
<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', 'your-pixel-id-goes-here');
  fbq('track', 'PageView');
</script>
<noscript>
  <img height="1" width="1" style="display:none" 
       src="https://www.facebook.com/tr?id=your-pixel-id-goes-here&ev=PageView&noscript=1"/>
</noscript>
<!-- End Facebook Pixel Code -->
```

**Standard Events**
- Upon viewing the event detail root or /tickets of an event with a related facebook pixel initiated the `ViewContent` event should be triggered
```
fbq('track', 'ViewContent',
  {
    content_ids: ['bigneon_event_id'],
    eventref: 'fb_oea' // or set to empty string
  }
);
```
- Upon adding tickets to cart the `InitiateCheckout` event should be triggered
```
fbq('track', 'InitiateCheckout',
  {
    content_ids: ['bigneon_event_id'],
    eventref: 'fb_oea' // or set to empty string
  }
);
```
- Upon completing the ticket purchase the `Purchase` event should be triggered
```
fbq('track', 'Purchase',
  {
    content_ids: ['bigneon_event_id'],
    eventref: 'fb_oea' // or set to empty string
    currency: 'USD'  // your currency string value goes here
    num_items: 1, // your number of tickets purchased value goes here
    value: 15.30, // your total transaction value goes here
  }
);
```
Special Properties:
- **content_ids**: Single item array with the Big Neon event ID
- **eventref**: If the referrer URL contains eventref=fb_oea as a query string parameter, then set this property's value to 'fb_oea'. Otherwise, set it to an empty string ('').

**Comment by mikethetike** [comment]
I'm getting these warning for ViewContent:
> This pixel is not paired with any product catalog. Please associate this pixel with a catalog using the Catalog Manager at https://www.facebook.com/products/.

> content_type is missing, should be either 'product' or 'product_group'

**Comment by zmelamed** [comment]
This hasn't been added at the event level per:
`An org member should be able to set a Facebook Pixel for a specific event which will override the org level Facebook Pixel`

Can we make sure that we get a ticket in the backlog to capture that @tas

**Comment by Tas4tari** [comment]
@zmelamed @mikethetike Issue has been created: https://github.com/big-neon/bigneon/issues/218

**Comment by Anziskavds** [comment]
Tested on Prod as an admin I was able to set a Facebook pixel and the integrations updated successfully. 

https://cl.ly/f74fe910eef8
https://cl.ly/c05872cfa515
