### ISSUE TITLE
Ticket Settings - Updating ticket types shouldn't update unchanged Sale start dates

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#183]
Connected to big-neon/bn-web#1524

Context: When an existing ticket type has a pre-set sale start date (like "Immediately") and you try and update that ticket type or any other ticket type, it attempts to update the sale start date and time for all ticket types with that pre-set to the current date and time. 

This causes a lot of issues, including blocking the saving of updates by throwing errors when any (not just the ticket type being updated) ticket sale end date has already passed--in that case you get an error that the ticket end date needs to be after the ticket sale start date and saving fails but it's impossible for the end user to know what caused that error.

Screencast: https://cl.ly/fe836d07e0de

**Comment by Jasonvdb** [comment]
Got some backend support incoming from @mikethetike https://github.com/big-neon/bn-api/issues/1324

**Comment by Anziskavds** [comment]
Tested on Prod and works as expected.

**Comment by harrisonlemon** [comment]
@zmelamed @Anziskavds @Jasonvdb Can we please reopen the issue? This is not resolved - see screengrab here https://cl.ly/555e3ff052a7
