### ISSUE TITLE
Fees: Credit Card Processing Fee does not appear on fee schedule overview

### ISSUE THREAD

**Issue by harrisonlemon** [big-neon/bigneon#184]
**Steps to reproduce:**
1. Add a per order credit card processing fee (ie 2.75%)
2. View the org fee schedule

**Expect to see:**

After setting the per order credit card processing fee, I expect to see the credit card processing fee listed in the fee schedule overview in the 'Order Fees' section. 

Saw instead:

The credit card processing fee was not included, and the total order fees was $0.

Screengrab here: https://cl.ly/53eeff63a9ce

**Comment by Tas4tari** [comment]
@Anziskavds Please test this for the release today

**Comment by Anziskavds** [comment]
Tested on Develop and looks like it is working as expected.

https://cl.ly/3a269aec807c

**Comment by Anziskavds** [comment]
Tested in Beta and is working as expected.

**Comment by Anziskavds** [comment]
Tested on Prod and is working as expected
