### ISSUE TITLE
Analytics/Sharing - Custom link generator for campaign tracking

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bigneon#189]
Context: A promoter should be able to generate a custom trackable shortened URL through a link builder. The builder would have presets for tracking common channels like Facebook, Email, Twitter, Instagram, etc. and would applicable to shared promo/hold codes. This link would deeplink into the mobile app or web app and track the data up to the transaction.

**Comment by zmelamed** [comment]
@Tas4tari here are the wires: https://share.goabstract.com/696e7053-2aae-4f9c-b800-648e6c210fc7

**Comment by Anziskavds** [comment]
Tested Prod on Web and Mobile Web and is working as expected
