### ISSUE TITLE
Event Management - Cancelling an event does not take ticket types offsale or update event status

### ISSUE THREAD

**Issue by harrisonlemon** [big-neon/bigneon#192]
Steps to reproduce:
1. From the event in the event listing, click 'Cancel Event' 
2. 'View Event'
3. Follow the purchase flow & buy tickets to the cancelled event

**Expect to see:** 

By selecting "Cancel Event" I expect that all ticket sales would end immediately (ticket sale end time = now). I also expect the purchase button on the Event Display page to reflect the new event status and no longer be a clickable 'Purchase' button. This button should reflect the current show status of 'Cancelled' or 'Off Sale' and not be click through to the purchase page.

**What I saw instead:**

When an event is cancelled, the 'purchase' button is still active and tickets for the event are still available to purchase. This poses the risk of selling tickets to a show that has been cancelled, postponed, or are otherwise unavailable. 

Screengrab: https://cl.ly/a01bb242a481

**Comment by Tas4tari** [comment]
@Anziskavds Please check this in Develop as well as this fix is going in

**Comment by Anziskavds** [comment]
Tested on Develop and is not working as expected.

https://cl.ly/571902fa7df6

**Comment by Tas4tari** [comment]
The "Purchase" button on the event is still clickable and still redirects you to the Purchase page. As per the requirement this button should no longer be clickable and should reflect as "Cancelled" or "Off Sale"

**Comment by ridley-tari** [comment]
@Tas4tari here is copy for a cancelled event page. Let me know if I'm too late on this or if it was a handled another way?

Sorry, this event is no longer available. [link]Browse other events[/link]

[Show other events at same venue, if no events at venue show other events in city, if no events in city show all events]

cc @Krakaw

**Comment by harrisonlemon** [comment]
Additionally: 'Purchase' button on the EDP should update to status 'Cancelled.'  The 'Cancelled' button should not allow a user to click through to the purchase page.

If a user access the purchase page directly, user should not be able to select ticket type quantities. 'Offsale' messaging should replace ticket type quantity selector.

**Comment by Anziskavds** [comment]
Tested on develop and it tested successful. https://cl.ly/8919c68bce5c

**Comment by harrisonlemon** [comment]
@Anziskavds The 'cancelled' status button is white with light gray text - it's a bit hard to see. Possible to keep the button style the same as the other buttons (pink/white)?

**Comment by Anziskavds** [comment]
Tested successful on Beta for web and mobile web.

**Comment by Anziskavds** [comment]
Tested successful on Prod on web and mobile web
