### ISSUE TITLE
Ticket Settings - Ticket types default to onsale 'Immediately' when sale start time is set by price tier

### ISSUE THREAD

**Issue by harrisonlemon** [big-neon/bigneon#195]
REL: #183 

Context: When the start time of a ticket type is set to 'When sales end for...' the ticket type saves as start time 'immediately.' 

This forces the user to update the ticket type onsale time each time an event edit is made. I also creates uncertainty around the accuracy of the actual start time of the ticket time. 

Screengrab: https://cl.ly/555e3ff052a7

**Comment by Tas4tari** [comment]
@Jasonvdb This defect has failed the QA process on Beta

**Comment by Jasonvdb** [comment]
@Tas4tari just tested on prod and it works fine? https://cl.ly/20305074b6a7

**Comment by Tas4tari** [comment]
@Anziskavds Please confirm this in Prod as per @Jasonvdb comment above

**Comment by Anziskavds** [comment]
@Tas4tari @Jasonvdb Tested on Prod and is working as expected.
