### ISSUE TITLE
Event State - Event is 'saved as draft' in studio, but visible & onsale to public

### ISSUE THREAD

**Issue by harrisonlemon** [big-neon/bigneon#196]
**Steps to reproduce:**

1. Create a new event
2. Enter all required event details
3. Do not change the event publish default setting 
4. 'Save Draft'
5. View the event on the front end - event display page, purchase page, and cart tickets

**What I expect to see:**

When I save an event as a 'Draft' the event should NOT be published, and ticket types should not be available for purchase. 

**What I actually see:**

When saving an event as a 'Draft' the event automatically publishes immediately and ticket types are visible if the default 'publish immediately' setting is selected.

When attempting to cart tickets, the user receives the error: EVENT HAS NOT BEEN PUBLISHED.

Screengrab: https://cl.ly/16c3e329eafa
Screengrab: https://cl.ly/34fd00e7aaf3

**Comment by Krakaw** [comment]
@harrisonlemon only the people that have access to the event in the org can see it (unless you specifically know the url for the event) and even if you do you cannot purchase tickets. Would you prefer that when a member of the public stumbles on a `Draft` event they get a 404? Org members can use the view to preview what their event page will look like?

**Comment by mikethetike** [comment]
I'm going to see if I can check if the user has access to edit the event in the Event get, and only return ticket types if they are allowed

**Comment by mikethetike** [comment]
@Tas4tari @Anziskavds Please add this to our test case pack

**Comment by Anziskavds** [comment]
Added it on Testpad @mikethetike @Tas4tari

**Comment by harrisonlemon** [comment]
@Krakaw Because event publication information is a super-sensitive touchpoint, especially as we start to work with national tours, we will need to make sure that 'unpublished' truly means not published and not listed online in any capacity. This means that the event display page and event purchase page will not be visible or searchable; the event URL will not be available; search terms will render no return. The event will literally not exist to the consumer until the first publication date. 

If an event the event display or purchase pages are listed while in 'draft' mode or set to 'unpublished' we risk the event leaking critical, protected event details to the public preemptively. This could result in an agent cancelling an event outright because sensitive information was announced before approval. As soon as the public starts to find the event, it will spread like wildfire and cause general confusion - leading to an influx of customer service and social media inquiries.

If an event has been previously published, then set to unpublished at a later time, the consumer should reach the equivalent of a 404 page. 

The publication rules should apply regardless of permissions or admin status. For example: if an event is unpublished and not yet onsale, I should not be able to 'View Event,' click an active purchase tickets button, and continue to cart tickets. This will help with future event build resolutions.

**Comment by Anziskavds** [comment]
- Tested Beta on Web but it failed to work as expected. When I clicked on "Save Draft" I received an "invalid type: null, expected i64 at line 1 column 265".

https://cl.ly/67e49d962fec

**Comment by Anziskavds** [comment]
Tested Beta on Web and Mobile Web and the event does not appear on a users event list. Works as expected.

**Comment by Anziskavds** [comment]
Tested on Prod and is working as expected
