### ISSUE TITLE
Ticket Settings - Unable to set ticket type onsale date/time

### ISSUE THREAD

**Issue by harrisonlemon** [big-neon/bigneon#208]
User is unable to easily set ticket type onsale time. A dropdown menu with limited preset times populates over the regular dropdown menu for the onsale time. 

When the time is set, it defaults to UTC rather that the timezone of the venue.

Screengrab: https://cl.ly/b146df9ed87d

**Comment by mikethetike** [comment]
I think this might be solved by adding "autofill/autocomplete" = off in the html. Not 100% sure

**Comment by Jasonvdb** [comment]
Hot fix went to prod

**Comment by Anziskavds** [comment]
Tested on Develop, Beta and Prod and I didn't experience that issue. Seems like it's working as expected.
