### ISSUE TITLE
Marketing/Analytics - Clicking update on the marketing page leads to a 404 page when saving facebook pixel

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#216]
**Context**: Clicking update on the marketing page leads to a 404 page when saving facebook pixel

Screencast https://cl.ly/dd896702b219

rel: #182

**Comment by Anziskavds** [comment]
Tested on Develop and the Facebook pixel updated successful without an error. Beta is still not working. Beta 1.0.444 and Develop is on 1.0.445, should be because Beta is still on the previous version.

**Comment by Anziskavds** [comment]
Tested on Beta and is working as expected. Facebook pixel updates successfully

**Comment by Anziskavds** [comment]
Tested successful on prod
