### ISSUE TITLE
Marketing/Analytics - Facebook pixel value and num_items not reporting correctly after a purchase

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#217]
Context: After completing a purchase the event is properly sent to facebook but the Value is listed as `NaN` instead of the gross value of the order and `num_items` is listed as 0 instead of the total number of items.

![_56__Facebook_Pixel.png](https://images.zenhubusercontent.com/5c8c16315df6d54b7b125005/2bbb3664-9bd0-47cb-8bd6-8cc0795ad531)

rel: #182

**Comment by Anziskavds** [comment]
Tested on develop and it's not working as expected.

**Comment by Anziskavds** [comment]
Tested on Beta and is working as expected.

https://cl.ly/ce607d021604

**Comment by Anziskavds** [comment]
Tested successful on prod.

https://cl.ly/c05872cfa515

https://cl.ly/f74fe910eef8
