### ISSUE TITLE
Marketing: Facebook Pixel Integration: Set Facebook Pixel per event

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bigneon#218]
An org member should be able to set a Facebook Pixel for a specific event which will override the org level Facebook Pixel

**Comment by Tas4tari** [comment]
@Anziskavds  PR has been approved and merged, please check this

**Comment by Anziskavds** [comment]
Tested successfully on Develop and Beta

**Comment by Anziskavds** [comment]
Tested successfully on Prod.

https://cl.ly/c05872cfa515

https://cl.ly/f74fe910eef8
