### ISSUE TITLE
Transfer Drip - Add Sendgrid Category Tag and Unique Arguments to Transfer Emails

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#219]
**Context**: Sendgrid allows you to add a `category` attribute to emails which makes it easy to view email stats and track performance over time for specific categories of emails. You can also track specific information about an email using unique arguments. We need to add categories and unique arguments to all transfer emails

https://sendgrid.com/docs/for-developers/sending-email/unique-arguments/
https://sendgrid.com/docs/for-developers/sending-email/categories/

All transfer emails should contain a unique arg `event_id` and `days_until_event` (if this is substantially more complex it can be moved to a separate issue)

For Sender Confirmation email:
```
{
  "category": [
    "transfer",
    "transfer_sender",
    "transfer_confirmation"
  ]
}
```

For Receiver Confirmation email:
```
{
  "category": [
    "transfer",
    "transfer_receiver",
    "transfer_confirmation"
  ]
}
```

For Sender Drip emails:
```
{
  "category": [
    "transfer",
    "transfer_sender",
    "transfer_drip"
  ]
}
```

For Receiver Drip emails:
```
{
  "category": [
    "transfer",
    "transfer_receiver",
    "transfer_drip"
  ]
}
```

**Comment by Anziskavds** [comment]
Testing on Develop. I received both the sender and the receivers transfer confirmation emails. I'm waiting for the drip emails.

**Comment by Anziskavds** [comment]
Tested on Beta and the sender and receiver received transfer confirmation emails and the drip emails. Tested successful on Beta

**Comment by Anziskavds** [comment]
Busy testing this on Prod, I received both the transfer confirmation emails. I'm waiting for the drip emails.

**Comment by Anziskavds** [comment]
Testing on Prod, I received both the transfer confirmation emails. I'm waiting for the drip emails.

**Comment by Anziskavds** [comment]
Tested successful on Prod
