### ISSUE TITLE
Ticket Transfer Drip - Updated Cadence and Logic for Transfer Engagement

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#220]
**Context**:  When a ticket transfer is initiated the receiving and sending users should receive a series of notifications to help communicate the status of the transfer and drive the users to download the app and accept the transfers prior to the event.

This is an improvement to the logic used to satisfy #148 #181

This matrix defines the cadence: https://docs.google.com/spreadsheets/d/1houNlzDC5YBe_jaEQGAkGy_8dxtfaMtj1-OR4YEJmzk/edit?usp=sharing
Copy that will be used for all messages can be found here:
https://docs.google.com/document/d/1EvqCp1igG-wpyfu5pkMzLT0_7y-K6oCs5fLXY78bp4o/edit?usp=sharing

The cadence logic is as follows:
- If a sender sends a transfer to an address (phone or email) and that address is matched to an existing user in our system
  - The transfer will immediately be completed into the receiving users wallet
  - The sender will receive an email confirming the transfer was complete
  - The receiver will receive an email, sms, and push notification (depending on the information that is in the system) that will deeplink into their Big Neon app tickets view where they can find the ticket
- If a sender sends a transfer to an address (phone or email) and that address is not matched to an existing user in our system
  - The sender will receive an email confirming the transfer was initiated with an option to cancel the transfer
  - The receiver will receive an email or sms (depending on the information the sender provided) with instructions and a link to accept the transfer
  - The receiver and sender will be eligible to receive reminder drip notifications until the transfer is accepted or the event begins at the following cadence according to the matrix shared above:
    - Sender
      - Day 1-7 (until 7 days before the event) after sending will receive an email on: 
        - Day 1
        - Day 3
        - Day 7
      - Day 7 until 7 days prior to the event the sender will receive an email every Tuesday
      - Starting 7 Days prior to the event the sender will receive an email on 
        - T-7 Days
        - T-4 Days
        - T-1 Days
        - Day of Event (at 10am)
        - T-2 Hours to door (only if they had not initiated the transfer, or receive a notification within 3 hours of Door time)
    - Receiver
      - Day 1-7 after initiation will receive an email or SMS every day
      - Day 8 until 7 days prior to the event the receiver will receive an email  or SMS every Tuesday
      - Starting 7 Days prior to the event the receiver will receive an email or SMS every day
      - On the day of the event the receiver will receive an email or SMS
        - Day of Event (at 10am)
        - T-2 Hours to door (only if they had not initiated the transfer, or receive a notification within 3 hours of Door time)

Per the matrix shared above, in addition to the time since transfer was initiated, and time until the event the following sender/receiver statuss determine which messaging/templates should used and which channel messages will be sent through:

- Sender - email available (receiver unknown)
- Sender - email available (receiver known)

- Receiver (unknown) - email available
- Receiver (unknown) - sms available

- Receiver (known) - email available
- Receiver (known) - sms available
- Receiver (known) - push available

Additional attributes need to be added to the payload that gets send to the templates for each email:
`time_until_event_string`: 
- More than 1 day before the event: `only 7 days away`
- 1 day before the event: `tomorrow`
- Day of the event (10AM): `today`
- Day of the event (2 hrs before doors): `in 2 hours`

`days_until_event`: The number of days remaining until the event

**Comment by ridley-tari** [comment]
@Tas4tari are you waiting on anything from the business/product teams on this?

**Comment by Tas4tari** [comment]
@ridley-tari Currently no, just need to go through this with Engineering tomorrow during our next planning session to determine estimates and if there is anything outstanding that is required.

**Comment by harrisonlemon** [comment]
@Tas4tari Please see the updated Ticket Transfer Drip Copy & Cadence as approved by business on 7/22 here: https://docs.google.com/document/d/1cA3yXaY9pbigrUqmn-Y5YhCwgVFYgPLhANJhnOLJxYc/edit

**Comment by nine-tari** [comment]
@harrisonlemon Hey Harrison just a heads up I sent an access request for the doc if you have a chance. Going to grab this issue next.

**Comment by harrisonlemon** [comment]
Hi @nine-tari shared :)
