### ISSUE TITLE
Dates on fan management is the same on every activity cards

### ISSUE THREAD

**Issue by Anziskavds** [big-neon/bigneon#226]
Steps to reproduce:

- The dates on the fan management page is the same on all the activity cards, even if the activity didn't take place today it still shows the current date but different times. This appear on both web and mobile web. It appears to be the current date.

https://cl.ly/6bce29197f00
https://cl.ly/d43199e1db6b

**Comment by Jasonvdb** [comment]
@Anziskavds prod should be updated with the fix

**Comment by Anziskavds** [comment]
Tested successful on Prod on web and mobile web.
