### ISSUE TITLE
Fan profile looks rough when no data

### ISSUE THREAD

**Issue by CjS77** [big-neon/bigneon#32]

**Comment by CjS77** [comment]
![Screen Shot 2018-12-10 at 22.58.44.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b859d39dd074c0011bcdd3c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455f36b7191a37aed0c2e59415b4abe5d4a1f06a3a3dc78e2a436628f0e03edd66c5871c43f19a8bf8a1fbf03bf26824dd7beba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecc5cf24ce44b50a31a3066f43b.png)

**Comment by Jasonvdb** [comment]
Something @mikethetike is still working on.
In progress issue in bn-web: https://github.com/big-neon/bn-web/issues/430

**Comment by mikethetike** [comment]
@CjS77 It looks rough even with data in it :joy:

**Comment by Jasonvdb** [comment]
Closed in https://github.com/big-neon/bn-web/pull/571
