### ISSUE TITLE
Ticket Settings - Tickets on-sale date/time should have a setting to peg it to another tickets sold out date/status

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#41]
An org member should have an option to peg the ticket types on sale date/time based on another ticket type selling out/going off-sale rather than a specific date/time.

- Under the On Sale Time ticket settings there should be an option "or when another tickets sales end..."
  - When this is clicked the Date/Time selector should switch to a Ticket Type Selector and there should be the option to switch back to date/time mode
  - When a ticket is saved with this setting it should be hidden until the selected ticket type sells out or the sale ends.

Overall
- [ ] Product/Design QA and approval
- [ ] Functional QA and approval

![BigNeon_Studio__Copy_Updates__sketch.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59934f6113749d001f2f5c80/125516c66e82c728ace21e0d46ca9d9d0d878ca7b0daab56a054ffab16652863303b963b7484f72dac7d4412040a0aff194a4356bcbbd671f3e57862804e0ebfd96d5875c13813aeb08618b701ba228e498cb4ee824ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df34fe14a55a6163762e2752431.png)

![BigNeon_Studio__Copy_Updates__sketch.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59934f6113749d001f2f5c80/125516c66e82c728ace21e0d46ca9d9d0d878ca7b0daab56a054ffab16652863303b963b7484f72dac7d4412040a0aff194a4356bcbbd671f3e57862804e0ebfd96d5875c13813aeb08618b701ba228e498cb4ee824ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df34fe14b5cac13356be6732431.png)

**Comment by Jasonvdb** [comment]
Related to https://github.com/big-neon/bn-web/issues/961
