### ISSUE TITLE
Promo Codes - An org member should be able to create a Discount promo code

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#45]
child of big-neon/docs#19
**Discount Codes**:
A discount redemption code is associated with 1 to many ticket types for a specific event and must be unique within the context of that event, the discount code applies a discount on a per unit basis to tickets purchased within that allocation. 

When a user applies a discount code, the Ticket Types pricing shown to them within the app and during checkout should reflect the discounted price, and a message indicating the discount code has been applied should appear on all subsequent checkout views, order summaries, and reports.

- [ ] A discount code is created with the following attributes:
  - Name (this is used for generating reports)
  - Redemption Code (min 6 character non case sensitive, unique for that event)
  - Ticket Types (the ticket type(s) that the code can be applied to. 1 Ticket Type can have many discount codes)
  - Max Total Uses (the number of code uses across the life of the code)
  - Discount amount (required. entered in dollars by the end user or as a percentage)
  - Start Date (The date the code can start to be used)
  - End Date (The date the code should stop working)
  - Max Per Customer (defaults to null, maximum number of tickets a single user should be able to purchase with this code)

- [ ] Reports should show the promo code name as a line item below the ticket it was applied to with the adjusted price. See Reports here with promo codes applied: https://docs.google.com/spreadsheets/d/1n_cNbKFQ7NExPx42d5GYohwo2CxHWFUVAWgFoRCe8Vc/edit?usp=sharing

- [ ] A list of promo codes should be accessible through the Event dashboard view under `Tools`>`Promo Codes`

- [ ] An org member should be able to generate a link used to share a promo code
  - When this link is clicked it should direct the user to the event page with the code applied

- [ ]  An org member should be able to update and delete a promo code

- [ ] When a promo code is applied to the ticket types during the checkout flow the price should reflect the discounted price and a label should appear over each ticket type that the code applies to
  - [ ] `$X Discount Applied`
  - [ ] `X% Discount Applied`

Overall
- [ ] Product/Design QA and approval
- [ ] Functional QA and approval

![image](https://user-images.githubusercontent.com/456953/55295299-46e8d100-53c0-11e9-8aa8-b5193296bd4a.png)
![image](https://user-images.githubusercontent.com/456953/55295131-a34af100-53be-11e9-8433-16802c36f0b0.png)

**Comment by philipr-za** [comment]
In the description above the value of the discount offered by a code is specified in absolute dollar terms. I just wanted to confirm that this is the intended unit of the value as opposed to a percentage discount? i.e. a 10% discount?

**Comment by zmelamed** [comment]
@philipr-za what work is remaining on this?

**Comment by philipr-za** [comment]
@zmelamed @Jasonvdb @mikethetike I completed the backend implementation for it, it now just needs to be used in the front end. I listed what still had to happen on the front-end in my PR (listed above) from what I could see from using it. I will repeat it here for clarity:

To do on the front-end:

- Handle the new Discount order item when rendering the cart

- Allow for creating and managing discount codes on events including the two possible types of discounts (percentage and absolute)
- When querying discount codes to apply to a cart read the total number available (found in the new available field) and the per-user limit and display the limits
- When querying redemption codes via GET /redemption_code/{code} endpoint add the event_id as a query string to limit returned results i.e. GET /redemption_code/{code}?event_id=0000-000000-0000-0000

**Comment by zmelamed** [comment]
Feedback from QA:
- [ ] Update names/placeholders of fields
  - [ ] Name Field Placeholder text: "Please name this promo code" no hyphen
  - [ ] Code Field Label: "Promo Code"
  - [ ] Code Placeholder Text: remove the hyphen prefix
  - [ ] Ticket Types label should be "Select Ticket Types"
  - [ ] Remove "Discount in ..." label from form field (it's repetitive with the radio labels right above it)
  - [ ] "Starts" should be a dropdown that says "Now" as default, or "Custom...". If the user chooses custom it should show the date/time fields
  - [ ] "Ends" Should be a dropdown that says "Never" as default, or "Custom...". If the user chooses custom it should show the date/time fields
  - [ ] Change "Uses" to "Total Uses"
  - [ ] Change "Limit Per User" to "Limit Per Customer"
- [ ] When I go to edit the promo code, the Limit per customer that I had set is no longer there
- [ ] `Tools` menu item should be changed from `Discount Codes` to `Promo Codes`
- [ ] List view should have the title `Promo Codes` instead of `Discount Codes`
- [ ] List should show the `Total Used` for each promo code
- [ ] Reports
  - [ ] Reports are reporting sales based on the face value of the ticket instead of the discounted value and not using the Name of the promo below the ticket type name. The name itself should be reflected on the reports as a line item under the ticket type and the price should be reflected at the discounted price. This is currently reporting that they've generated more sales than they have if it's using the ticket face instead of the discounted value.
  - [ ] Transaction detail reports need to show the Promo Code (which is right now called the `Redemption Code` column) and discount amount so that the gross balances
- [ ] Update the designs of the consumer Ticket Selection view
  - [ ] Each line ticket type should that has the discount code applied it should show the label `X Discount Applied` above the ticket type price and name
  - [ ] The displayed price should update to reflect the discounted price
  - [ ] The input field should switch to the active state with a remove option to remove the promo code
![image (3).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59934f6113749d001f2f5c80/125516c66e82c728ace21e0d46e1999b2487c3e1dca0fd0fe64de29b234324676b5ee17e72ddb37fee152e535d574aab49585f46f9ff8029f4be3a62964e49bc8f3900299f7744eeaa880dbe06b0218e4a81b2be8f4ac8eb3d24ef99c2.png)

**Comment by zmelamed** [comment]
Please review report spec here to see how promo codes should be treated on the various reports: https://docs.google.com/spreadsheets/d/1n_cNbKFQ7NExPx42d5GYohwo2CxHWFUVAWgFoRCe8Vc/edit?usp=sharing
