### ISSUE TITLE
Promo Codes - An org member should be able to create ticket Access Codes

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#46]
child of big-neon/docs#19
**Access Codes**:
An access redemption code is associated with 1 to many ticket types for a specific event and must be unique within the context of that event, if an access code is active and associated with a ticket allocation, that ticket allocation will only be visible if that access code is supplied by the user.
A access code is created with the following attributes:
 - Name (this is used for generating reports)
 - Redemption Code (min 6 character non case sensitive, unique for that event)
 - Ticket Types (the ticket type(s) that the code can be applied to. 1 Ticket Type can have many access codes)
 - Max Uses (the number of code uses across the life of the code)
 - Start Date (The date the code becomes active and the ticket type is hidden from the general public)
 - End Date (The date the code is no longer active and the ticket type can be available to the general public)
 - Max Per User (defaults to null, maximum number of tickets a single user should be able to purchase with this code)
![image](https://user-images.githubusercontent.com/456953/47187948-a3b56b00-d2fb-11e8-8139-9cd795fceb35.png)

**Comment by philipr-za** [comment]
Addressed in https://github.com/big-neon/bn-web/pull/1315
