### ISSUE TITLE
Checkout - More informative app download "requirement" FAQ/Information

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#63]
Update language on the checkout page to read:
```
TO ACCESS YOUR TICKETS
GET THE BIG NEON APP

Important: To protect you from fraud and the spread of counterfeit tickets, printable tickets are not available. 

Download the Big Neon app and login to your account to access your tickets:
```
`[Download Buttons]`
`[Send SMS to Download Form]`
```
If you cant download the app (or don't want to) you can provide your ID and order information at the events will call desk. Make sure the name on your account matches your ID. 
```
"Make sure the name on your account matches your ID" should link to the account details page

![Checkout_confirmation@1x.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59934f6113749d001f2f5c80/125516c66e82c728ace21e0d46cb9c9f20898cbc9bd6bc4caa5bf9862447337a260a837a68c7af6aaf50740b0a0c0abe4b4a5a16f4f98e2aa1b33e7282580ce5d16d5d71c03413feb0840da313f871d51bdaebe5c01982fa3737e682854e3b1b071181fe553ca29e43ce4abb.png)

**Comment by Jasonvdb** [comment]
Updating the text input to `We can send a download link to your mobile device:` breaks the layout a bit on mobile so leaving that as is for now

**Comment by zmelamed** [comment]
Thanks
