### ISSUE TITLE
Order Fees - Credit card fees

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#64]
A super admin should be able to set credit card fee as a percentage for an org under the Other Fees setting of studio.

Credit card fees should be added to the total service fees of an order so that Total Service Fees = Service Fees before CC fees + [cc_fee_percentage * (Service Fees Before CC fees + Total Face)]

Overall
- [ ] Product/Design QA and approval
- [ ] Functional QA and approval

**Comment by philipr-za** [comment]
Just to make sure my understanding of how to handle this is correct here is what I was thinking:

If there is a non-zero cc_fee_percent for the org when a purchase is made the following will happen:
* An extra order_item with OrderItemType::CreditCardFees will be added to the order for these fees, calculated as described above
* The front end will add this fee into the Service Fees field on the checkout page
* On refund this fee will be ignored (not refunded)

Just checking this makes sense? @Krakaw @zmelamed

**Comment by Krakaw** [comment]
> The front end will add this fee into the Service Fees field on the checkout page
@zmelamed correct me if I'm wrong, this should never go back to the client that is purchasing a ticket, this is for us to use on the settlement report to deduct the cc fee that we were charged when processing the payment.

**Comment by zmelamed** [comment]
The customer ultimately pays this fee, it gets baked into the service fee, the settlement to the client should be the same, it's an added fee we tack on top of the current service fee and keep for ourselves.

>On refund this fee will be ignored (not refunded)
We refund the full amount charged.

So if customer buys a $9 ticket and that client fee schedule says that $9 tix equates to fees of  $0.75 to the client $0.25 to Big Neon--Pre-cc_fee_percent service fee = $1 in this scenario. If the client has a credit card fee associated with their org of 5%, then the service fee that is shown to the customer buying the ticket would become $1.50 (($9 + $1)* 5%) ... in settlement the client still gets the $9 ticket value + $0.75 rev share... so this doesn't impact the settlement to the client. This is just an added fee we keep. 

We should keep record of this fee separate for each order so we can pull more granular reports in the future, but in reports for now we'll just bake it into the "service fees" where applicable if that's easiest.

If that customer requests a refund we'd trigger a stripe refund for the full order, customer would be refunded the full 10.50.  Stripe would hold on to the actual CC fee, but the customer would get the $10.50 re-funded. We eat that cost for the time being.

**Comment by zmelamed** [comment]
@Krakaw @philipr-za What happens here when we deploy to prod and the venue doesn't have anything set for CC fee? does it default to 0? Just want to make sure it doesn't make anything explode in the ordering flow on prod vs staging :)

**Comment by philipr-za** [comment]
Yes the db migration defaults to 0
