### ISSUE TITLE
Checkout Flow - Mobile first web UI improvements

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#67]
We are implementing a mobile first redesign of the checkout flow.

A prototype of the desired experience can be viewed here: 
https://cl.ly/2e5814172d57

The design for the Ticket Selection View can be found here (collapsed ticket type descriptions): https://share.goabstract.com/5421e4c1-b2ea-420a-b859-8594f821832c and here (expanded ticket type descriptions): https://share.goabstract.com/5c453cf0-f888-4c2e-b66c-11db9a2cfdd7

The designs for the Order confirmation and payment view can be found here: https://share.goabstract.com/5407815b-5fb2-4ec8-abe1-66446ada5338 

Acceptance Criteria:
- [x] Ticket Selection View should take up the full width and height of the screen with the content area vertical aligned to the top of the view area scrollable only if the contents expands beyond the viewport
  - [x] If there is only 1 ticket type listed it should default to 1 ticket selected
  - [x] If there is more than 1 ticket type available they should default to 0 tickets selected
  - [x] If the ticket type has a description it should be accessible through a Read More text link toggle
    - [x] When Read More is clicked the ticket type description should expand down and the button should switch to Read Less
    - [x] When Read Less is clicked it should hide the description and switch the text link to Read More state
   - [x] The price, ticket type name, and qty area should remain fixed to the top of the cell and vertically centered relative to each other when the description is visible
- [x] Order confirmation and payment view should take up the full width and height of the screen with the content area vertically aligned to the top of the view area scrollable only if the contents expands beyond the viewport
  - [x] If there is only one payment method that method should be selected by default and no radio or icons should be present (ie. If only stripe payments by CC is enabled, then there should only be a the credit card input fields visible and no radio button sector or it's related icon)
- [ ] Order confirmation view on when loading on an iOS device should show a single call to action button that leads directly to the the app store with the link: https://itunes.apple.com/app/apple-store/id1445600728?pt=119447135&ct=checkout-confirmation&mt=8
- [ ] Order confirmation view on when loading on an Android device should show a single call to action button that leads directly to the the play store with the link: https://play.google.com/store/apps/details?id=com.bigneon.mobile&referrer=utm_source%3Dcheckout-confirmation%26utm_medium%3Dweb
- [x] Web view should show a form to text a link to the users device
  - [x] The texted link should detect the device type and direct the user to the correct app store based on their device

Overall
- [ ] Designer QA and approval
  - Typography matches the spec'd design
  - Margins and padding match the spec'd design
  - Page structure matches the spec' design
- [ ] Functional QA and approval

![image](https://user-images.githubusercontent.com/456953/55054992-edc71900-501e-11e9-8b4f-800fb89fb87b.png)
![image](https://user-images.githubusercontent.com/456953/55054999-f4559080-501e-11e9-9e13-41db44926cb8.png)
![Mobile_Checkout_confirmation_v6.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59934f6113749d001f2f5c80/125516c66e82c728ace21e0d46c59b982a8e8696ace1ba40af52e5801645287d2f0db1267191ea27b17d6d574d435cec03070511afbd9b21b4b36e788a5b0aead46f5d7cc23a19acb8801ab908b872834997aaaec81d9ebc6278bec1da0d2c14171980f55c30a59d4acd5dfe42e24c5ca5017b.png)

**Comment by zmelamed** [comment]
![image](https://user-images.githubusercontent.com/456953/55054992-edc71900-501e-11e9-8b4f-800fb89fb87b.png)
![image](https://user-images.githubusercontent.com/456953/55054999-f4559080-501e-11e9-9e13-41db44926cb8.png)
![image](https://user-images.githubusercontent.com/456953/55055003-f881ae00-501e-11e9-8cbf-a773e8e41876.png)

**Comment by zmelamed** [comment]
@Jasonvdb added links to abstract file for copy, will share Lottie json file with you

**Comment by zmelamed** [comment]
@Jasonvdb after reviewing this we've decided we're going to simplify these views. The animated illustration is really distracting and there is way too much going on on the pages that draws the user away from the primary call to action. 

Zhenya is going to clean these up slightly but wanted to put them in front of you asap: https://share.goabstract.com/e6156989-f1fd-4244-849e-be78d0051f09
![Checkout_confirmation_v3@1x.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59934f6113749d001f2f5c80/125516c66e82c728ace21e0d46cb9c9f20898cbc9bd6bc4caa5bf9862447337a260a9c3d23a5b230fd0e39111d0014f9121c4d4eeefcdb23a6b13d778f5e09e5d56a5774c63f14aab1804db707a83c990dd4e8e8d51199a26867f5819d4e3914041d8cfb5c30a39b42cc5bf34cf300.png)
![Mobile_Checkout_confirmation_v6.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59934f6113749d001f2f5c80/125516c66e82c728ace21e0d46c59b982a8e8696ace1ba40af52e5801645287d2f0db1267191ea27b17d6d574d435cec03070511afbd9b21b4b36e788a5b0aead46f5d7cc23a19acb8801ab908b872834997aaaec81d9ebc6278bec1da0d2c1417198ef55c30a59d4acd5bf442e54e50a7017b.png)

**Comment by Jasonvdb** [comment]
@zmelamed I'm using the Android/iOS icon depending on the phone but I think using the branch link (https://bigneon.app.link/BnTAUQaEJS) would be better instead of the direct app store links as it'll handle the deep linking if the app happens to be installed. What do you think?


![Screenshot 2019-04-02 at 11 47 12](https://user-images.githubusercontent.com/5300488/55393287-4590e300-553d-11e9-9a8c-3f1c86cf7ec7.png)
![Screenshot 2019-04-02 at 11 48 28](https://user-images.githubusercontent.com/5300488/55393289-4590e300-553d-11e9-8730-3f99c8d64d44.png)
