### ISSUE TITLE
Box Office - If I only have private (hold only) ticket types available I can't sell from the hold

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#69]
Current behavior:
If I create an event and all ticket types are private (hold required) I can't sell from the hold in the box office view. The bottom action bar is hidden until I add a publicly available ticket type.

Acceptance Criteria:
- [ ] A box office attendant should be able to sell from a hold when no General public tickets are listed

Overall
- [ ] Product/Design QA and approval
- [ ] Functional QA and approval

**Comment by Krakaw** [comment]
I couldn't get this to work on my side, going to re-open so we can address it in the morning, as well as have a look at the missing (Remove Promo Button) 
![image](https://user-images.githubusercontent.com/41575888/55975353-163f4c00-5c8a-11e9-97b7-6c9c180caf0d.png)

**Comment by philipr-za** [comment]
Just for clarity the original Issue asked for the ability to sell Private ticket types via the holds. Selling tickets that are hidden by Access promo codes will be added now.

**Comment by philipr-za** [comment]
Also going to add that the access codes field autocompletes on all access codes for this event.

**Comment by philipr-za** [comment]
So in the end I opted to just query and show all ticket types for the event, even those that are hidden by an Access code. This way the Box Office person can see all available ticket types and choose accordingly. 

I removed the Promo/Hold Code input box as it is redundant.
