### ISSUE TITLE
Event Images - Event images should be changed to an aspect ratio of 1.91:1 recommended 1920 x 1080

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#70]
To reduce the number of assets a promoter needs to create, we should use the commonly used aspect ratio of 1.91:1 and a recommended 1920 x 1080 px's so our images can seamlessly be used for FB event cover images.

Acceptance Criteria:
- [x] Event creation image uploader shows recommended image size and aspected ratio of aspect ratio of 1.91:1 and 1920 x 1080 px
- [x] Event creation image cropper enforces aspect ratio of  1.91:1
- [x] Aspect ratio is enforced throughout consumer experience
- [x] Aspect ratio is enforced throughout studio experience

Overall
- [ ] Product/Design QA and approval
- [ ] Functional QA and approval

**Comment by Jasonvdb** [comment]
@zmelamed just confirming you want the uploader to enforce 1.91:1? The ratio of a 1920 x 1080 image is 1.777:1

**Comment by zmelamed** [comment]
Enforce 1920px x 1080px ratio... that's what PW uses. Finding mixed info on the best practice
