### ISSUE TITLE
My Events - UX Improvements/Bugs

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#71]
Acceptance Criteria:
- [ ] Title should be "My Events"
- [ ] Events list should be tabbed to filter `Upcoming` and `Past` events
  - [ ] Upcoming should be default and should sort in ascending order
  - [ ] Past should show events in descending order 
- [ ] Clicking the "View My Tickets" button should do scroll the user back to the top of the page (disable default click event behavior)
- [ ] Transfer ticket UI should not have a QR code
- [ ] Some (but not all) events show Invalid Date Time (see screen attached)

Overall
- [ ] Product/Design QA and approval
- [ ] Functional QA and approval

![Big_Neon_-_The_new_standard_in_event_ticketing.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59934f6113749d001f2f5c80/125516c66e82c728ace21e0d46ca9d9d1cac86a681d6f27c9055f5ab2743304c3a10a2257484f12c804b753e0a191bf205371b1dafa2dc6fffe86b62964e4baf8e370a27822f1bbebdd017bf06bb278e4d87beb88d44c0e83f20e1828d1d361817049bbd0c6bf4c6169112a309f34747a51b3c62e3733574469c1d7c2d686020b9b1.png)

**Comment by Jasonvdb** [comment]
@zmelamed another thing to consider is the mobile version of this page is badly broken. Maybe we can have a designer look at a mobile version and I can update that at the same time.

**Comment by zmelamed** [comment]
I'm going to break this apart into separate issues so that we can move what we can forward while we organize designs

**Comment by zmelamed** [comment]
The mobile designs may take some time, the designers backlogs are pretty full with other hi-pri work and we need to improve this so I broke this out to:
#103 
#104 
#105 
#106 
#107 
#108
