### ISSUE TITLE
Reports - Event Transaction detail report exports are only showing a single page of data. Should show full report for the selected range

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#83]
Exporting a transaction detail report for an event only exports a single page worth of data instead of the full report.

**Comment by Jasonvdb** [comment]
@Krakaw I got this

**Comment by zmelamed** [comment]
@Krakaw @Jasonvdb this looks good if it's ready to go live and hasn't yet please pull the trigger

**Comment by Jasonvdb** [comment]
I see it's live now
