### ISSUE TITLE
Ticket Settings - Org member should be able to set visibility when ticket is unavailable

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#88]
**Context**: We've had client requests to allow for a ticket to be visible when it is sold out, and when it is not yet on sale during an early bird sale for instance, to imply scarcity. We currently allow the consumer to set the visibility when a ticket type sells out but there is no option to set the visibility in other states when the allocation exists but is is not yet on sale, sale has ended. I believe we can improve our Sold Out visibility setting by expanding it to a `Ticket Type Visibility` setting

A user should be able to set the visibility of a ticket when it is not yet on sale, sale has ended, or the ticket is sold out.
- Under additional settings for a ticket type a user should be able to select one of two options for **Ticket Type Visibility**:
  - **Always Visible** (Default setting)
  - **Only When Available**
  - **Promo/Hold Code Required**
- If a ticket is set to **Always Visible** when unavailable:
  - If the ticket is not yet on sale, meaning the on sale date/time is in the future or awaiting another tickets off-sale (such as an early bird allocation) it should have the label **On Sale Soon** instead of the quantity selector
  - If a ticket sale has ended, meaning the end time of the sale has been reached or the event has ended, it should have the label **Sale Ended** instead of the quantity selector
  - If a ticket is not sold out, but all remaining tickets are in holds/carts, it should have the label **Unavailable** instead of having the quantity selector
  - If a ticket sale is sold out, it should have the label Sold Out instead of having the quantity selector
- If a ticket is set to **Only When Available**:
  - The ticket should not be shown to the consumer if it is not yet on sale, sale has ended, all tickets are in holds or the ticket is sold out.
- If a ticket is set to **Promo/Hold Code Required**:
  - The ticket should not be hidden unless a hold or promo code associated with that ticket type is applied

**Consumer Label UI:**
https://share.goabstract.com/1668be48-a680-4a4b-a2fe-e353804f72e3
![image](https://user-images.githubusercontent.com/456953/56051837-bd60c980-5d04-11e9-9f1b-62579227a7be.png)

**Comment by mikethetike** [comment]
Is there an option to have the ticket type hidden when Sold out, but visible as "On Sale Soon"?

**Comment by zmelamed** [comment]
@mikethetike I checked with PW and Jessi and we don't think that's a case we need to cover. Most people will either do **Always Visible** or **Only When Available**.

Another point if it's not clear is that this will replace the use of the private checkbox. Promo/Hold Code Required will cover that.

I re-pinged Karim, but don't yet have the hi-fi designs so sharing the consumer view wires for now so you can visualize the expected outcome
![FAN_Checkout_status_labels_low_fi.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59934f6113749d001f2f5c80/125516c66e82c728ace21e0d46ceb5b41ca18bac8ce2b056b062e380285232601608a2297589f017b34d6c3e09065cb053181d1ba6acda6fb4bc2e75d8540bead06a5a76c43515abb0821fbd04bc29891d8db0ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4ecd58f643e24e50a7153f71ab.png)

**Comment by zmelamed** [comment]
@mikethetike @Jasonvdb I've added the designs for the labels to the description above

**Comment by Jasonvdb** [comment]
@mikethetike is working on the studio and api changes, I'll hop on and update the consumer UI when he's done
