### ISSUE TITLE
Event Summary Report - Promo Codes - Event summary report doesn't report all discount code sales data, total value does not calculate correctly

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#89]
relates to big-neon/bigneon#45
Event Summary Report doesn't report all discount code sales data, total value does not calculate correctly ($50 * 8 does not equal $365) (https://cl.ly/8671becb52d6 & https://cl.ly/e56ae83b4a1e)

**Comment by Jasonvdb** [comment]
Should be fixed in https://github.com/big-neon/bn-web/pull/1329
