### ISSUE TITLE
Event Summary Report - Promo Codes - When both full price and discounted tix are purchased together, reports show all as discounted

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#90]
relates to big-neon/bigneon#45
When a full price ticket is carted & purchased in the same transaction as a discounted ticket, the Event Summary Audit considers all tickets discounted but the total value does not calculate correctly (https://cl.ly/1d7e0582c100 and https://cl.ly/1cfc2426cf01)

**Comment by Jasonvdb** [comment]
Should be fixed in https://github.com/big-neon/bn-web/pull/1329
