### ISSUE TITLE
Event Audit Report - All Events section not breaking down promos and full price ticket line items

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#91]
relates to big-neon/bigneon#45
Event Audit Report partially reports discount code redemptions/sales (https://cl.ly/7d64ff6b2030)
All Events section does not include discount code sales data, total value does not calculate correctly within the table ($50 * 8)

**Comment by Jasonvdb** [comment]
Should be fixed in https://github.com/big-neon/bn-web/pull/1329
