### ISSUE TITLE
Checkout - Promo Codes - Received error that promo code failed but order succeeded

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#95]
relates to big-neon/bigneon#45
Received 'Failed to Apply Promo Code' on order confirmation screen, post purchase (https://cl.ly/58fa427e7ded). Verified promo code use for order against transaction detail report, appears to have been successful.

**Comment by Jasonvdb** [comment]
@zmelamed I ran through all these promo codes on that event (https://beta.bigneon.com/events/bb390ab0-fb34-4284-b2bb-25427c82d253) and didn't manage to replicate the error. Is there anything else you did before checking out that I can use to test and try replicate?

![Screenshot 2019-04-09 at 09 30 50](https://user-images.githubusercontent.com/5300488/55781330-31536580-5aaa-11e9-9f12-cb630ccb1b5d.png)

**Comment by zmelamed** [comment]
k can close it if you can't reproduce, if it pops back up we'll re-open
