### ISSUE TITLE
Promo Codes - Mobile Optimized Promo Code List UI

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#99]
**Context:** A user should be able to view the list of active promo codes on mobile web and quickly see in a table:
- Name of Promo Code
- Code
- Num Used
- Active/Inactive status
  - Hidden on Mobile:
  - Button to copy Code to clip board
  - Button to copy share link to clip board
  - Button to edit code
  - Type (Discount or Access)
  - Discount (Either a %, $, or none if it's an access code) 
  - Remaining (Number of remaining uses)
  - Ticket Types (See designs: Label should take the grey state when not yet on sale, green state when on sale and available, and the pink state when sold out)
    - On Desktop:
      - If the list of Ticket Types exceeds the available space:
        - The number of additional ticket types should be displayed as `+##` on hover a tooltip should display all of the ticket types 

**Action Buttons:**
- If a user clicks the new Discount Code button they should see a form to create a new Discount Code
- If a user clicks the new Access Code button they should see a form to create a new Access Code
- If a user clicks the Copy Code icon they should see a success message that the code has been successfully copied
- If a user clicks the Copy Link icon they should see a success message that the link has been successfully copied
- If a user clicks the Edit icon they should see a form to edit the code details
- A user should be able to typeahead search the list of codes by Code and by name which filters the table

Mobile https://share.goabstract.com/e57dc2ba-a0c1-48cf-9701-a29ff27fb1ff:
![image](https://user-images.githubusercontent.com/456953/56512873-7da89780-64e5-11e9-92bb-4fdbb461b4ca.png)
Desktop https://share.goabstract.com/7daaeda4-4cbe-4da7-a86e-c917e929dd9a:
![image](https://user-images.githubusercontent.com/456953/56512893-8f8a3a80-64e5-11e9-961c-2a0dd3998f59.png)

**Comment by Jasonvdb** [comment]
@zmelamed for the active/inactive status dot. Just confirming that's calculated using the start/end time for discount codes? And for access codes it'll always be green.

**Comment by Jasonvdb** [comment]
Once https://github.com/big-neon/bn-api/issues/1228 is closed the ticket type color tags should reflect correctly.

**Comment by Jasonvdb** [comment]
Moving the search box request into it's own issue as I'm waiting on a shared search box component that's being worked on. https://github.com/big-neon/bn-web/issues/1382
